# Generated by Django 4.0.2 on 2023-01-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_book_publisher_store_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='location',
            field=models.CharField(default='Lahore', max_length=300, null=True),
        ),
    ]
